language: rust
sudo: false

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: iwJM3WKH92yxKSdRkab/R8nO3BRzxyxK3QvyPBH2gEUhd1/ZTjLQcWbpF9Gv0Kpkbm1hNAAPTNN787qNFv8qJ/Ebr+VTkxpAQrh1wX37fMF1gqWdaSeZQM0xeCzptoOrIz/FgbBcTV7ndx+Fc4g0dwtfBPZf2/blwg4F9CjqbYpnc5M3iNN9GuLwBU3FCM4nr5OyqZji+EweoxAN3bk17lmlCoTlggap2MY5MHGo+vslMvlAvd7vj1dNCo8ytQC4VyfUriXSQKmKSFl7WHsEQm6hIWvMLVDx6zyUvYfZfYqtmuthiAAj56tVpXCzNoI/v2bjMDlAajoQsn3arTEmL21CugsEsc6nvmEpbuziw9WPLBKdgBALepbHDncLLo4vLXexJOwZgZKoAK/DqboFjW9nevxbJh6Qz0LyRMKdSNUgxe90i/yNxcQaEJHoonB5QjAgTfzMmHCm+4tAiwp8S6sqg8GNKIaTo7Tt40mxFycXIC73YnIe5whLDbrcyJIozntL03B+VeMZMCKNfl+Q63O3NCnxSpog6rQSNYNXazUk2CzT7PonQ72j0b8WFpl1kBtuG4zctN2+t7toi0rJnd7vPfUMs0G2p4LRZ5VESoqOrFHKwEtSS7xIKUuscfCPNUcVvb9aWoAJNTdw/ouLARVQMOk/jscf6SU50zuszhU=

notifications:
  email: false
