language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench;
      cargo build;
      cargo test;
    else
      cargo build;
      cargo test;
    fi

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: n0wYyA0rTr0ScX40ehFxX9A+rL4n33QcdCXAy/1Qj0giFGXP0HHc0dwO0YFoj8nU8HdG1omDz+48uYZI1Od7dlQm1HkXL53OCJDan0SUfsYM5jv1Dl20aUucUeDT/EbolNRqTbaXAxQYiNlaqioWL6KqQAwjOgwV0r9U7o4T+xThjhd/YS6lUZHT/7pl2If7mtHw+5IKY9Vl5xYLBKPDMVCraeEXTFCJosBFpIZKuKrWFrywmEsK/cxnCHXPvzYAQry/lwNsEB3RQBBySGbyLNdhEx3aadl39v8mDZ7+vzGuSaKdYsUf18TkzlmtPHvfOvDigits8YYxnXTc3ouH4XJI+RrMTMhVBxQM2AN48jPgIVWYLjH1Db+N7ZKoIdlyk2VHzg4VKUConZt0JMmux802nid4zLBCLzVxnLhvhziVaSQ2BG81gwWtDtvGF8tuBmcUFjLcH/5s8ipy1lYkoV1WGpiikKrQMLJnx7y54FYiadE2TlwT4XsWD0tOgTDr+m+Reyb0n/91chG3m0RV9eu0ylT34LqMvJ7wPzySKmzt0fUTJUWDUHDXyhYhFXJhglnAnJdpUNXRgpf85fpAwi2cxD9VQrLnQmyldUl+RFeG8a2oQiynd5nksOqj5+wJienB2sk5W0MfCo397ZIVG41udz/UKuabOqfZneSMRaY=

notifications:
  email: false
