[package]
name = "fft"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/fft"
homepage = "https://github.com/stainless-steel/fft"
documentation = "https://stainless-steel.github.io/fft"
description = """
The package provides an algorithm to compute the discrete Fourier transform and
its inverse."""

[dependencies]
complex = "*"

[dev-dependencies]
assert = "*"
