[package]
name = "dft"
version = "0.2.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/dft"
homepage = "https://github.com/stainless-steel/dft"
documentation = "https://stainless-steel.github.io/dft"
description = """
The package provides an algorithm to compute the discrete Fourier transform."""

[dependencies]
complex = "0.7"

[dev-dependencies]
assert = "0.6"
