[package]
name = "fft"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/fft"
homepage = "https://github.com/hilbert-space/fft"
description = """
The package provides an algorithm to compute the discrete Fourier transform and
its inverse."""

[dev-dependencies]
assert = "*"
