[package]
name = "dft"
version = "0.4.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/dft"
homepage = "https://github.com/stainless-steel/dft"
documentation = "https://stainless-steel.github.io/dft"
description = """
The package provides an algorithm to compute the discrete Fourier transform."""

[dependencies.num]
version = "0.1"
features = ["complex"]
default-features = false

[dev-dependencies]
assert = "0.6"
